name: workflow, job and step level env variables

on: push

# workflow level env variables
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME:   siddharth1
    IMAGE_NAME: github-actions-nginx

jobs:
    docker_job:
# job level env variables
       env:
         CONTAINER_REGISTRY: docker.io
       runs-on: ubuntu-latest
       steps:
            - name: Docker Build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

            - name: Docker Login
# step level env variables
              env: 
                DOCKER_PASSWORD: s3cUrePaSsw0rd
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy_job:
        needs: docker_job   #this job runs after docker_job job. Thus avoid default parallel execution
        runs-on: ubuntu-latest
        steps:
           - name: Docker Run
             run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


            
